### PR TITLE
Fix menu bar update frequency

### LINKED ISSUE #373: Import not available
When trying to import into an unlocked archive, the import options are not available:

image

### PR DESCRIPTION
**Pull request by sallar**
Fixes #373

### CODE REVIEW

File: src/main/actions.js [hunk 1]
```diff
@@ -11,6 +12,9 @@ export function setupActions(store) {
   // Clear update notice
   store.dispatch(updateInstalled());
 
+  // Update the menu
+  store.subscribe(debounce(() => setupMenu(store), 500));
```
Comment (perry-mitchell) [inline src/main/actions.js]: Why debounce menu creation? Isn't 500ms maybe a bit much?

Comment (sallar) [reply src/main/actions.js]: Its not menu creation. Everytime the store updates (any action regardless of it having anything to do with menu or not) this re-draws the menu which is slightly heavy process. And sometimes this function (subcribed function) gets called 20 times in 100ms. So just wanted to avoid performance issues and lags

Comment (perry-mitchell) [reply src/main/actions.js]: 👍
