### PR TITLE
Fixed Biometrics Crash

### LINKED ISSUE #993: Buttercup 2.0.0 not opening on Windows 10
Buttercup was working fine, but after unistalling and installing the 2.0.0 for Windows x64 downloaded from Github, the program won't open. Not even a process is initialized in Task Manager.

### PR DESCRIPTION
**Pull request by Alternus**
Fixed the crash due to `TypeError: electron_1.systemPreferences.canPromptTouchID is not a function` mentioned in #990 and likely also the cause of #993. 
Currently tested this on Manjaro Linux.

EDIT: Fixes #993

### CODE REVIEW

File: source/main/services/biometrics.ts [hunk 1]
```diff
@@ -67,7 +67,11 @@ export async function sourceEnabledForBiometricUnlock(sourceID: VaultSourceID):
 }
 
 export async function supportsBiometricUnlock(): Promise<boolean> {
-    return systemPreferences.canPromptTouchID();
+    try {
+        return systemPreferences.canPromptTouchID();
+    } catch (err) {
+        return false;
+    }
```
Comment (vikaspotluri123) [inline source/main/services/biometrics.ts:74]:
```suggestion
	if (process.platform === 'darwin') {
        return systemPreferences.canPromptTouchID();
    }

    return false;
```

I don't think it really matters either way 😄

Comment (jy95) [reply source/main/services/biometrics.ts:74]: In [Electron docs](https://www.electronjs.org/docs/api/system-preferences#systempreferencescanprompttouchid-macos), it is written that `systemPreferences.canPromptTouchID()` is a MacOS-only feature. So it really don't matter ...
