### PR TITLE
Fix whitespace issue when editing tree items

### LINKED ISSUE #439: Can't type space into group title input
When adding a new group or renaming one, "space" character can't be typed.

### PR DESCRIPTION
**Pull request by sallar**
Fixes #439

### CODE REVIEW

File: src/renderer/components/tree-view/tree-label-edit.js [hunk 1]
```diff
@@ -46,6 +46,7 @@ class LabelEditor extends Component {
 
   handleKeyUp(e) {
     const { title } = this.state;
+    console.log(e.keyCode);
```
Comment (perry-mitchell) [inline src/renderer/components/tree-view/tree-label-edit.js]: Umm.. Should be kill 'dis?

Comment (sallar) [reply src/renderer/components/tree-view/tree-label-edit.js]: Oops!

File: src/renderer/components/tree-view/tree-label-edit.js [hunk 2]
```diff
@@ -32,7 +32,7 @@ class LabelEditor extends Component {
   }
 
   handleChange(e) {
-    this.setState({ title: e.target.value.trim() });
+    this.setState({ title: e.target.value });
```
Comment (perry-mitchell) [inline src/renderer/components/tree-view/tree-label-edit.js]: 👍👍👍👍👍
